[project]
name = "chatbot-with-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "colorlog>=6.10.1",
    "fastapi>=0.118.0",
    "langchain-chroma>=0.2.6",
    "langchain-docling>=1.1.0",
    "langchain-google-community[calendar]>=2.0.10",
    "langchain-google-genai>=2.1.12",
    "langchain-groq>=0.3.8",
    "langgraph>=0.6.8",
    "langgraph-checkpoint-sqlite>=2.0.11",
    "pydantic-settings>=2.11.0",
    "python-multipart>=0.0.20",
    "uvicorn>=0.37.0",
]
