"""create user_settings and remove routine timezone

Revision ID: 0a4649db206c
Revises: 05ee90e6fc2a
Create Date: 2026-01-16 20:48:40.350136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4649db206c'
down_revision: Union[str, Sequence[str], None] = '05ee90e6fc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    # op.drop_column('routines', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('routines', sa.Column('timezone', sa.VARCHAR(), server_default=sa.text("'Asia/Dhaka'::character varying"), autoincrement=False, nullable=False))
    op.drop_table('user_settings')
    # ### end Alembic commands ###
