"""Add score and difficulty to quizzes

Revision ID: 3b04f219324f
Revises: 31542e6e822d
Create Date: 2026-02-12 10:42:51.848834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b04f219324f'
down_revision: Union[str, Sequence[str], None] = '31542e6e822d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('quizzes', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'score')
    op.drop_column('quizzes', 'difficulty')
    # ### end Alembic commands ###
