"""add_routine_and_class_session_tables

Revision ID: 3fd7577a98e7
Revises: b22dab0f2638
Create Date: 2026-01-12 18:17:27.954525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd7577a98e7'
down_revision: Union[str, Sequence[str], None] = 'b22dab0f2638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    op.create_table('class_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_class_sessions_routine_id_routines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_sessions')
    op.drop_table('routines')
    # ### end Alembic commands ###
