"""change folder cascade delete

Revision ID: b60c7e15ef05
Revises: cd18245b619a
Create Date: 2026-01-30 18:21:00.806109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b60c7e15ef05'
down_revision: Union[str, Sequence[str], None] = 'cd18245b619a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversations_folder_id_folders', 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_conversations_folder_id_folders'), 'conversations', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_files_folder_id_folders', 'files', type_='foreignkey')
    op.create_foreign_key(op.f('fk_files_folder_id_folders'), 'files', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_files_folder_id_folders'), 'files', type_='foreignkey')
    op.create_foreign_key('fk_files_folder_id_folders', 'files', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_conversations_folder_id_folders'), 'conversations', type_='foreignkey')
    op.create_foreign_key('fk_conversations_folder_id_folders', 'conversations', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
