"""add_mindmap_table

Revision ID: e7cf40d1f5d6
Revises: 5a61fc351d4d
Create Date: 2026-02-11 09:04:12.160560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7cf40d1f5d6'
down_revision: Union[str, Sequence[str], None] = '5a61fc351d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mindmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('mindmap_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_mindmaps_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_mindmaps_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_mindmaps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mindmaps'))
    )
    op.create_index(op.f('ix_mindmaps_conversation_id'), 'mindmaps', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_mindmaps_folder_id'), 'mindmaps', ['folder_id'], unique=False)
    op.create_index(op.f('ix_mindmaps_user_id'), 'mindmaps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mindmaps_user_id'), table_name='mindmaps')
    op.drop_index(op.f('ix_mindmaps_folder_id'), table_name='mindmaps')
    op.drop_index(op.f('ix_mindmaps_conversation_id'), table_name='mindmaps')
    op.drop_table('mindmaps')
    # ### end Alembic commands ###
