"""remove external_sub from users

Revision ID: 135b8e40d826
Revises: ac0907707d6f
Create Date: 2025-12-31 13:14:17.535799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135b8e40d826'
down_revision: Union[str, Sequence[str], None] = 'ac0907707d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_sub'), table_name='users')
    op.drop_column('users', 'external_sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_sub', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_external_sub'), 'users', ['external_sub'], unique=True)
    # ### end Alembic commands ###
