"""add folder conversation fk to quiz

Revision ID: 31542e6e822d
Revises: 7cd736a3561d
Create Date: 2026-02-11 20:10:29.855899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31542e6e822d'
down_revision: Union[str, Sequence[str], None] = '7cd736a3561d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.add_column('quizzes', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_quizzes_conversation_id'), 'quizzes', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_quizzes_folder_id'), 'quizzes', ['folder_id'], unique=False)
    op.create_foreign_key(op.f('fk_quizzes_folder_id_folders'), 'quizzes', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_quizzes_conversation_id_conversations'), 'quizzes', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quizzes_conversation_id_conversations'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('fk_quizzes_folder_id_folders'), 'quizzes', type_='foreignkey')
    op.drop_index(op.f('ix_quizzes_folder_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_conversation_id'), table_name='quizzes')
    op.drop_column('quizzes', 'conversation_id')
    op.drop_column('quizzes', 'folder_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
