"""add user_id to routines

Revision ID: 702de27d4d97
Revises: 4b294746c28a
Create Date: 2026-02-01 20:02:16.375391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '702de27d4d97'
down_revision: Union[str, Sequence[str], None] = '4b294746c28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear existing routines to avoid NotNullViolation when adding non-nullable user_id
    op.execute("TRUNCATE TABLE routines CASCADE")
    
    op.add_column('routines', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_routines_user_id_users'), 'routines', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_routines_user_id_users'), 'routines', type_='foreignkey')
    op.drop_column('routines', 'user_id')
    # ### end Alembic commands ###
