"""replace time with start_time and end_time in class_sessions

Revision ID: 805b22dd50b8
Revises: 3fd7577a98e7
Create Date: 2026-01-14 20:51:19.901851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805b22dd50b8'
down_revision: Union[str, Sequence[str], None] = '3fd7577a98e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('class_sessions', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('class_sessions', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('class_sessions', 'end_time')
    op.drop_column('class_sessions', 'start_time')
    # ### end Alembic commands ###
