"""remove given_name

Revision ID: b22dab0f2638
Revises: 0fe026202743
Create Date: 2026-01-10 12:50:37.999986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22dab0f2638'
down_revision: Union[str, Sequence[str], None] = '0fe026202743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'given_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
